// Copyright 2026 Marc-Antoine Ruel. All Rights Reserved. Use of this
// source code is governed by the Apache v2 license that can be found in the
// LICENSE file.

package commentcheck

import (
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"
)

// writeModule writes a one-package module, changes into it, and returns its
// Package.
func writeModule(t *testing.T, files map[string]string) Package {
	t.Helper()
	dir := t.TempDir()
	t.Chdir(dir)
	all := map[string]string{"go.mod": "module p\n\ngo 1.27\n"}
	for name, src := range files {
		all[name] = src
	}
	for name, src := range all {
		path := filepath.Join(dir, name)
		if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(src), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	pkgs, err := ListPackages([]string{"./..."})
	if err != nil {
		t.Fatal(err)
	}
	if len(pkgs) != 1 {
		t.Fatalf("got %d packages: %v", len(pkgs), pkgs)
	}
	return pkgs[0]
}

// runCheck returns the violation messages for the files, with absolute paths
// made relative for stable assertions.
func runCheck(t *testing.T, files map[string]string) []string {
	t.Helper()
	pkg := writeModule(t, files)
	vs, err := Check(pkg)
	if err != nil {
		t.Fatal(err)
	}
	out := make([]string, 0, len(vs))
	for i := range vs {
		out = append(out, strings.TrimPrefix(vs[i].String(), pkg.Dir+"/"))
	}
	return out
}

func TestCheck(t *testing.T) {
	t.Run("valid", func(t *testing.T) {
		cases := []struct {
			name  string
			files map[string]string
		}{
			{"documented declarations", map[string]string{"a.go": `package p

// Foo does X.
func Foo() {}

// Bar is a type.
type Bar struct{}

// A is a method.
func (b *Bar) A() {}
`}},
			{"unexported declarations need no doc", map[string]string{"a.go": `package p

func foo() {}

type bar struct{}

func (b *bar) a() {}
`}},
			{"method on unexported receiver needs no doc", map[string]string{"a.go": `package p

func foo() {}

type bar struct{}

func (b *bar) Exported() {}
`}},
			{"well-known interface methods need no doc", map[string]string{"a.go": `package p

func (b *Buf) Read(p []byte) (int, error) { return 0, nil }

func (b *Buf) Write(p []byte) (int, error) { return 0, nil }

func (b *Buf) Close() error { return nil }

func (b *Buf) String() string { return "" }

func (e *Err) Error() string { return "" }

func (w *Wrap) Unwrap() error { return nil }
`}},
			{"values need no doc", map[string]string{"a.go": `package p

const (
	A = 1
	b = 2
)

var (
	C = 3
	d = 4
)
`}},
			{"detached comment not naming a declaration", map[string]string{"a.go": `package p

// Section header.

// Foo does X.
func Foo() {}
`}},
			{"comment inside a function", map[string]string{"a.go": `package p

// Foo does X.
func Foo() {
	// Bar helper below.
	Bar()
}

// Bar does Y.
func Bar() {}
`}},
			{"comment above a directive line", map[string]string{"a.go": "package p\n\n// foo does X.\n\n//go:noinline\nfunc foo() {}\n"}},
			{"directive comments are ignored", map[string]string{"a.go": `//go:build linux

package p

//go:generate stringer -type=Foo

// Foo does X.
func Foo() {}
`}},
			{"generated file skipped", map[string]string{
				"a.go": `package p

// Foo does X.
func Foo() {}
`,
				"gen.go": `// Code generated by gen DO NOT EDIT.

package p

func Bar() {}
`,
			}},
			{"doc comment of a grouped decl", map[string]string{"a.go": `package p

// Foo does X.
type (
	Foo struct{}
)
`}},
			{"test file needs no docs", map[string]string{
				"a.go": `package p

// Foo does X.
func Foo() {}
`,
				"a_test.go": `package p

func TestFoo(t *T) {}
`,
			}},
		}
		for _, c := range cases {
			t.Run(c.name, func(t *testing.T) {
				if got := runCheck(t, c.files); len(got) != 0 {
					t.Fatalf("got violations:\n%s", strings.Join(got, "\n"))
				}
			})
		}
	})
	t.Run("error", func(t *testing.T) {
		cases := []struct {
			name  string
			files map[string]string
			want  []string
		}{
			{
				"exported function without doc",
				map[string]string{"a.go": "package p\n\nfunc Foo() {}\n"},
				[]string{"a.go:3: exported declaration Foo has no doc comment"},
			},
			{
				"exported free function named like a common method still needs a doc",
				map[string]string{"a.go": "package p\n\nfunc String() string { return \"\" }\n"},
				[]string{"a.go:3: exported declaration String has no doc comment"},
			},
			{
				"exported type without doc",
				map[string]string{"a.go": "package p\n\ntype Foo struct{}\n"},
				[]string{"a.go:3: exported declaration Foo has no doc comment"},
			},
			{
				"exported method without doc",
				map[string]string{"a.go": "package p\n\n// Foo is a type.\ntype Foo struct{}\n\nfunc (f *Foo) A() {}\n"},
				[]string{"a.go:6: exported declaration A has no doc comment"},
			},
			{
				"doc not starting with the name",
				map[string]string{"a.go": "package p\n\n// This does X.\nfunc Foo() {}\n"},
				[]string{"a.go:3: doc comment for Foo should start with \"Foo\""},
			},
			{
				"doc starting with a superstring of the name",
				map[string]string{"a.go": "package p\n\n// Foobar does X.\nfunc Foo() {}\n"},
				[]string{"a.go:3: doc comment for Foo should start with \"Foo\""},
			},
			{
				"detached by a blank line",
				map[string]string{"a.go": "package p\n\n// Foo does X.\n\nfunc Foo() {}\n"},
				[]string{
					"a.go:3: doc comment for Foo is detached by a blank line",
					"a.go:5: exported declaration Foo has no doc comment",
				},
			},
			{
				"detached by two blank lines",
				map[string]string{"a.go": "package p\n\n// Foo does X.\n\n\nfunc Foo() {}\n"},
				[]string{
					"a.go:3: doc comment for Foo is detached by a blank line",
					"a.go:6: exported declaration Foo has no doc comment",
				},
			},
			{
				"detached comment for another declaration",
				map[string]string{"a.go": "package p\n\n// Bar does Y.\n\nfunc Foo() {}\n\n// Bar does Z.\nfunc Bar() {}\n"},
				[]string{
					"a.go:3: detached doc-like comment for Bar before Foo; move it next to the declaration or reword it",
					"a.go:5: exported declaration Foo has no doc comment",
				},
			},
			{
				"comment detached by code between declarations",
				map[string]string{"a.go": "package p\n\n// Bar does Y.\nconst c = 1\n\n// Foo does X.\nfunc Foo() {}\n"},
				nil,
			},
		}
		for _, c := range cases {
			t.Run(c.name, func(t *testing.T) {
				got := runCheck(t, c.files)
				if len(got) != len(c.want) {
					t.Fatalf("got %v, want %v", got, c.want)
				}
				for i := range got {
					if !strings.HasPrefix(got[i], c.want[i]) {
						t.Fatalf("got %q, want prefix %q", got[i], c.want[i])
					}
				}
			})
		}
	})
}

func TestCheckFixes(t *testing.T) {
	t.Run("detach fix removes the blank lines", func(t *testing.T) {
		pkg := writeModule(t, map[string]string{"a.go": "package p\n\n// Foo does X.\n\nfunc Foo() {}\n"})
		vs, err := Check(pkg)
		if err != nil || len(vs) != 2 {
			t.Fatalf("got %v, %v", vs, err)
		}
		fix := vs[0].Fix
		if fix == nil {
			t.Fatal("expected a fix")
		}
		if fix.File != filepath.Join(pkg.Dir, "a.go") || fix.Start != 4 || fix.End != 4 || fix.Text != "" {
			t.Fatalf("got %+v", fix)
		}
	})
	t.Run("move fix relocates the comment", func(t *testing.T) {
		pkg := writeModule(t, map[string]string{"a.go": "package p\n\n// Bar does Y.\n\nfunc Foo() {}\n\nfunc Bar() {}\n"})
		vs, err := Check(pkg)
		if err != nil || len(vs) != 3 {
			t.Fatalf("got %v, %v", vs, err)
		}
		fix := vs[0].Fix
		if fix == nil {
			t.Fatal("expected a fix")
		}
		if fix.Start != 3 || fix.End != 3 || fix.Text != "// Bar does Y." || fix.DstLine != 7 {
			t.Fatalf("got %+v", fix)
		}
	})
	t.Run("no fix when the target is documented", func(t *testing.T) {
		pkg := writeModule(t, map[string]string{"a.go": "package p\n\n// Bar does Y.\n\nfunc Foo() {}\n\n// Bar does something else.\nfunc Bar() {}\n"})
		vs, err := Check(pkg)
		if err != nil || len(vs) != 2 {
			t.Fatalf("got %v, %v", vs, err)
		}
		if vs[0].Fix != nil {
			t.Fatalf("expected no fix, got %+v", vs[0].Fix)
		}
	})
	t.Run("no fix for missing doc comments", func(t *testing.T) {
		pkg := writeModule(t, map[string]string{"a.go": "package p\n\nfunc Foo() {}\n"})
		vs, err := Check(pkg)
		if err != nil || len(vs) != 1 {
			t.Fatalf("got %v, %v", vs, err)
		}
		if vs[0].Fix != nil {
			t.Fatalf("expected no fix, got %+v", vs[0].Fix)
		}
	})
	t.Run("violations are sorted by file then line", func(t *testing.T) {
		pkg := writeModule(t, map[string]string{
			"a.go": "package p\n\nfunc Zed() {}\n\nfunc Abc() {}\n",
			"b.go": "package p\n\nfunc A() {}\n",
		})
		vs, err := Check(pkg)
		if err != nil || len(vs) != 3 {
			t.Fatalf("got %v, %v", vs, err)
		}
		if a, b, c := vs[0], vs[1], vs[2]; filepath.Base(a.File) != "a.go" || a.Line != 3 || b.Line != 5 || filepath.Base(c.File) != "b.go" {
			t.Fatalf("not sorted: %v, %v, %v", a, b, c)
		}
	})
	t.Run("xtest files are checked", func(t *testing.T) {
		got := runCheck(t, map[string]string{
			"a.go":        "package p\n\n// Foo does X.\nfunc Foo() {}\n",
			"a_x_test.go": "package p_test\n\n// Bar does Y.\n\nfunc Bar() {}\n",
		})
		want := []string{"a_x_test.go:3: doc comment for Bar is detached by a blank line"}
		if !slices.Equal(got, want) {
			t.Fatalf("got %v, want %v", got, want)
		}
	})
}
