// Copyright 2026 Marc-Antoine Ruel. All Rights Reserved. Use of this
// source code is governed by the Apache v2 license that can be found in the
// LICENSE file.

package commentcheck

import (
	"bytes"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/golangci/plugin-module-register/register"
	"golang.org/x/tools/go/analysis"
)

func TestRegistered(t *testing.T) {
	newPlugin, err := register.GetPlugin("commentcheck")
	if err != nil {
		t.Fatal(err)
	}
	p, err := newPlugin(map[string]any{})
	if err != nil {
		t.Fatal(err)
	}
	if p.GetLoadMode() != register.LoadModeSyntax {
		t.Fatalf("got %q", p.GetLoadMode())
	}
	analyzers, err := p.BuildAnalyzers()
	if err != nil {
		t.Fatal(err)
	}
	if len(analyzers) != 1 || analyzers[0].Name != "commentcheck" {
		t.Fatalf("got %+v", analyzers)
	}
	if _, err := newPlugin(map[string]any{"nope": 1}); err == nil {
		t.Fatal("expected an error on unknown settings")
	}
}

// applyEdits applies the edits to the source, like golangci-lint's fixer would.
func applyEdits(t *testing.T, fset *token.FileSet, src []byte, edits []analysis.TextEdit) []byte {
	t.Helper()
	type rng struct {
		start, end int
		text       []byte
	}
	rs := make([]rng, len(edits))
	for i, e := range edits {
		rs[i] = rng{fset.Position(e.Pos).Offset, fset.Position(e.End).Offset, e.NewText}
	}
	slices.SortFunc(rs, func(a, b rng) int { return a.start - b.start })
	var out []byte
	prev := 0
	for _, r := range rs {
		out = append(out, src[prev:r.start]...)
		out = append(out, r.text...)
		prev = r.end
	}
	return append(out, src[prev:]...)
}

// write writes a source file to disk.
func write(t *testing.T, path, src string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(src), 0o600); err != nil {
		t.Fatal(err)
	}
}

func TestSuggestedEdits(t *testing.T) {
	cases := []struct {
		name string
		src  string
	}{
		{"detach", "package p\n\n// Foo does X.\n\nfunc Foo() {}\n"},
		{"move", "package p\n\n// Bar does Y.\n\nfunc foo() {}\n\nfunc Bar() {}\n"},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			dir := t.TempDir()
			path := filepath.Join(dir, "a.go")
			write(t, path, c.src)
			fset := token.NewFileSet()
			f, err := parser.ParseFile(fset, path, c.src, parser.ParseComments)
			if err != nil {
				t.Fatal(err)
			}
			vs := CheckSyntax(fset, []*ast.File{f})
			// Pick the violation carrying a fix; the declarations it names may
			// additionally miss doc comments, which have no fix.
			var v *Violation
			for i := range vs {
				if vs[i].Fix != nil {
					v = &vs[i]
					break
				}
			}
			if v == nil {
				t.Fatalf("expected one violation with a fix, got %+v", vs)
			}
			edits, ok := suggestedEdits(fset, *v)
			if !ok || len(edits) != 1 {
				t.Fatalf("expected one edit, got %v, %v", edits, ok)
			}
			// Edits must be sorted and non-overlapping.
			last := -1
			for _, e := range edits {
				start := fset.Position(e.Pos).Offset
				if start < last {
					t.Fatalf("edits are not sorted: %d after %d", start, last)
				}
				last = fset.Position(e.End).Offset
			}
			fixed := applyEdits(t, fset, []byte(c.src), edits)
			// golangci-lint runs the configured formatters over fixed files, so
			// compare gofmt clean on both sides.
			got, err := format.Source(fixed)
			if err != nil {
				t.Fatalf("fixed file does not parse: %v\n%s", err, fixed)
			}
			want, err := v.Fix.Contents()
			if err != nil {
				t.Fatal(err)
			}
			if !bytes.Equal(got, want[v.Fix.File]) {
				t.Fatalf("fixed content disagrees with Contents:\n%s\nwant:\n%s", got, want[v.Fix.File])
			}
		})
	}
}

func TestRunReports(t *testing.T) {
	dir := t.TempDir()
	src := "package p\n\n// Bar does Y.\n\nfunc foo() {}\n\nfunc Bar() {}\n"
	path := filepath.Join(dir, "a.go")
	write(t, path, src)
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, path, src, parser.ParseComments)
	if err != nil {
		t.Fatal(err)
	}
	var got []analysis.SuggestedFix
	pass := &analysis.Pass{
		Analyzer: &analysis.Analyzer{Name: "commentcheck"},
		Fset:     fset,
		Files:    []*ast.File{f},
		Report: func(d analysis.Diagnostic) {
			got = append(got, d.SuggestedFixes...)
		},
	}
	out, err := pluginRun(pass)
	if err != nil || out != nil {
		t.Fatalf("got %v, %v", out, err)
	}
	// Three violations: the detached comment with a suggested fix, and the two
	// missing doc comments without one.
	if len(got) != 1 || !strings.Contains(got[0].Message, "Re-attach or move the comment") {
		t.Fatalf("got %+v", got)
	}

	// Generated files are not reported.
	genPath := filepath.Join(dir, "gen.go")
	genSrc := "// Code generated by x DO NOT EDIT.\npackage p\n\nfunc Nope() {}\n"
	write(t, genPath, genSrc)
	gen, err := parser.ParseFile(fset, genPath, genSrc, parser.ParseComments)
	if err != nil {
		t.Fatal(err)
	}
	got = nil
	pass.Files = []*ast.File{f, gen}
	if _, err := pluginRun(pass); err != nil {
		t.Fatal(err)
	}
	if len(got) != 1 {
		t.Fatalf("got %+v", got)
	}
}
